### ISSUE TITLE
Rotary encoder doesn't work after reboot.

### ISSUE THREAD

**Issue by MrPi3141** [volumio/Volumio2#1977]
The rotary encoder doesn't work when Volumio is restarted. I have to go into the plugin settings and click save every time I want to use the encoder.

**Comment by Saiyato** [comment]
Hi @MrPi3141 , this has already been addressed and fixed as of version 1.2.4 :)

**Comment by MrPi3141** [comment]
Thanks for the feedback. Issue remains unfortunately. We're running the latest version of Volumio on a RPi3B and justboom amp hat. Have tried a couple of encoders, but same issue.  Any help appreciated.

**Comment by Saiyato** [comment]
Hi, can you please add some logging? There's debug logging available to explode logging

**Comment by MrPi3141** [comment]
Thanks, here's the log from just now. I have marked where the plugin settings were saved which allows the encoder to function. Prior to that, nothing happened when I turned the encoder.

`volumio@volumio:~$ sudo journalctl -f
-- Logs begin at Thu 2020-06-11 19:09:56 UTC. --
Jun 11 19:12:12 volumio volumio[1073]: info: Plugin example_plugin is not enabled
Jun 11 19:12:12 volumio volumio[1073]: info: Loading plugin "inputs"...
Jun 11 19:12:12 volumio volumio[1073]: info: Loading plugin "updater_comm"...
Jun 11 19:12:12 volumio sudo[1292]: volumio : TTY=pts/0 ; PWD=/home/volumio ; USER=root ; COMMAND=/bin/journalctl -f
Jun 11 19:12:12 volumio sudo[1292]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Jun 11 19:12:12 volumio volumio[1073]: info: Plugin mpdemulation is not enabled
Jun 11 19:12:12 volumio volumio[1073]: info: Loading plugin "rest_api"...
Jun 11 19:12:12 volumio volumio[1073]: info: Loading plugin "websocket"...
Jun 11 19:12:12 volumio volumio[1073]: info: Loading plugin "touch_display"...
Jun 11 19:12:12 volumio volumio[1073]: Forking 3 albumart workers
Jun 11 19:12:13 volumio volumio[1073]: info: Loading plugin "rotaryencoder"...
Jun 11 19:12:13 volumio volumio[1073]: Starting albumart workers
Jun 11 19:12:13 volumio volumio[1073]: Starting albumart workers
Jun 11 19:12:13 volumio volumio[1073]: Starting albumart workers
Jun 11 19:12:14 volumio volumio-remote-updater[639]: [2020-06-11 19:12:14] [connect] Successful connection
Jun 11 19:12:14 volumio volumio[1073]: info: Applying required configuration parameters for plugin rotaryencoder
Jun 11 19:12:14 volumio volumio[1073]: info: ___________ START PLUGINS ___________
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Jun 11 19:12:14 volumio volumio[1073]: info: [1591902734341] CoreMusicLibrary::Adding element Media Servers
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jun 11 19:12:14 volumio volumio[1073]: info: Could not detect Primo: Error: Command failed: aplay -l | grep es90x8q2m-dac-dai-0
Jun 11 19:12:14 volumio volumio[1073]: info: Could not detect Primo: Error: Command failed: aplay -l | grep es90x8q2m-dac-dai-0
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Jun 11 19:12:14 volumio volumio[1073]: info: [1591902734496] CoreMusicLibrary::Adding element Last_100
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Jun 11 19:12:14 volumio volumio[1073]: info: [1591902734502] CoreMusicLibrary::Adding element Webradio
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
Jun 11 19:12:14 volumio volumio[1073]: info: [Rotary encoder] Loaded configuration: {"longPressThresholdInMilliseconds":{"type":"int","value":1000},"first_encoder_CLK":{"type":"int","value":14},"first_encoder_DT":{"type":"int","value":15},"first_encoder_SW":{"type":"int","value":0},"first_encoder_encoding":{"type":"int","value":0},"first_encoder_detentActionType":{"type":"int","value":1},"first_encoder_buttonActionType":{"type":"int","value":0},"first_encoder_longPressActionType":{"type":"int","value":0},"second_encoder_CLK":{"type":"int","value":0},"second_encoder_DT":{"type":"int","value":0},"second_encoder_SW":{"type":"int","value":0},"second_encoder_encoding":{"type":"int","value":0},"second_encoder_detentActionType":{"type":"int","value":0},"second_encoder_buttonActionType":{"type":"int","value":0},"second_encoder_longPressActionType":{"type":"int","value":0},"enable_debug_logging":{"type":"boolean","value":true}}
Jun 11 19:12:14 volumio volumio[1073]: info: -------------------------------------------
Jun 11 19:12:14 volumio volumio[1073]: info: -----    MyVolumio plugins startup     ----
Jun 11 19:12:14 volumio volumio[1073]: info: -------------------------------------------
Jun 11 19:12:14 volumio volumio[1073]: info: [MyVolumio PluginManager] Fetching plans data....
Jun 11 19:12:14 volumio sudo[1347]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl start volumio-kiosk.service
Jun 11 19:12:14 volumio volumio[1073]: info: Loading i18n strings for locale en
Jun 11 19:12:14 volumio sudo[1347]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:14 volumio volumio[1073]: Updating browse sources language
Jun 11 19:12:14 volumio volumio[1073]: Cannot find translation for sourceMedia Servers
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jun 11 19:12:14 volumio systemd[1]: Started Start Volumio Kiosk.
Jun 11 19:12:14 volumio sudo[1347]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::initPlayerControls
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getAlsaCards
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
Jun 11 19:12:14 volumio volumio[1073]: info: BOOT COMPLETED
Jun 11 19:12:14 volumio volumio[1073]:  [Metrics]  CommandRouter:  9s 40.09ms
Jun 11 19:12:14 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Jun 11 19:12:14 volumio kernel: pcm512x 1-004d: No SCLK, using BCLK: -2
Jun 11 19:12:18 volumio dhcpcd[549]: timed out
Jun 11 19:12:18 volumio dhcpcd[549]: exited
Jun 11 19:12:18 volumio ifup[515]: dhcpcd[549]: timed out
Jun 11 19:12:18 volumio ifup[515]: dhcpcd[549]: exited
Jun 11 19:12:18 volumio ifup[515]: Failed to bring up eth0.
Jun 11 19:12:19 volumio volumio[1073]: Playing WAVE '/volumio/app/startup.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Jun 11 19:12:19 volumio volumio[1073]: info: CoreCommandRouter::Close All Modals sent
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::Close All Modals sent
Jun 11 19:12:20 volumio volumio[1073]: Express server listening on port 3000
Jun 11 19:12:20 volumio volumio[1073]:  [Metrics]  WebUI:  15s 715.20ms
Jun 11 19:12:20 volumio volumio[1073]: Volumio Calling Home
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::resetVolumioState
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::getcurrentVolume
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::volumioRetrievevolume
Jun 11 19:12:20 volumio sudo[1370]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig eth0
Jun 11 19:12:20 volumio sudo[1370]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:20 volumio sudo[1372]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Jun 11 19:12:20 volumio sudo[1370]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:20 volumio sudo[1372]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:20 volumio sudo[1372]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:20 volumio volumio[1073]: info: Volumio called home
Jun 11 19:12:20 volumio volumio[1073]: info: Setting Device type: Raspberry PI
Jun 11 19:12:20 volumio volumio[1073]: info: Volumio Kiosk Started
Jun 11 19:12:20 volumio volumio[1073]: info: Kiosk Started
Jun 11 19:12:20 volumio volumio[1073]: info: MPD running with PID704
Jun 11 19:12:20 volumio volumio[1073]: ,establishing connection
Jun 11 19:12:20 volumio volumio[1073]: info: VolumeController:: Volume=35 Mute =false
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::pushState
Jun 11 19:12:20 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::volumioPushState
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::updateTrackBlock
Jun 11 19:12:20 volumio volumio[1073]: info: CorePlayQueue::getTrackBlock
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::volumioRetrievevolume
Jun 11 19:12:20 volumio volumio[1073]: error: updateQueue error: null
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::setRepeat false single undefined
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::pushState
Jun 11 19:12:20 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::volumioPushState
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::setRandom null
Jun 11 19:12:20 volumio volumio[1073]: info: CoreStateMachine::pushState
Jun 11 19:12:20 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::volumioPushState
Jun 11 19:12:20 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 11 19:12:22 volumio volumio[1073]: info: Reloading queue from file
Jun 11 19:12:22 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , checkAudioDeviceAvailable
Jun 11 19:12:22 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: raat , onStop
Jun 11 19:12:22 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , versionChangeDetect
Jun 11 19:12:22 volumio volumio[1073]: info: VolumeController:: Volume=35 Mute =false
Jun 11 19:12:22 volumio volumio[1073]: info: CoreStateMachine::pushState
Jun 11 19:12:22 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:22 volumio volumio[1073]: info: CoreCommandRouter::volumioPushState
Jun 11 19:12:22 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Jun 11 19:12:22 volumio volumio[1073]: info: Starting Shairport Sync
Jun 11 19:12:22 volumio volumio[1073]: info: Starting Shairport Sync
Jun 11 19:12:22 volumio sudo[1397]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart shairport-sync
Jun 11 19:12:22 volumio sudo[1397]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:22 volumio sudo[1400]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart shairport-sync
Jun 11 19:12:22 volumio sudo[1400]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:22 volumio systemd[1]: Starting Shairport Sync - AirPlay Audio Receiver...
Jun 11 19:12:22 volumio systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Jun 11 19:12:22 volumio systemd[1410]: Failed at step GROUP spawning /usr/local/bin/shairport-sync: No such process
Jun 11 19:12:22 volumio sudo[1406]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl start upmpdcli.service
Jun 11 19:12:22 volumio systemd[1]: shairport-sync.service: main process exited, code=exited, status=216/GROUP
Jun 11 19:12:22 volumio systemd[1]: Unit shairport-sync.service entered failed state.
Jun 11 19:12:22 volumio sudo[1406]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:22 volumio sudo[1397]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:22 volumio systemd[1]: Starting UPnP Renderer front-end to MPD...
Jun 11 19:12:22 volumio systemd[1]: Started UPnP Renderer front-end to MPD.
Jun 11 19:12:22 volumio systemd[1]: Starting Shairport Sync - AirPlay Audio Receiver...
Jun 11 19:12:22 volumio systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Jun 11 19:12:22 volumio sudo[1400]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:22 volumio volumio[1073]: Discovery: adding 61787f1e-427b-4619-823c-e4b751c84bc6
Jun 11 19:12:22 volumio volumio[1073]: info: mDNS: Found device Volumio
Jun 11 19:12:22 volumio sudo[1406]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:22 volumio volumio[1073]: info: CoreCommandRouter::volumioGetState
Jun 11 19:12:22 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:22 volumio systemd[1419]: Failed at step GROUP spawning /usr/local/bin/shairport-sync: No such process
Jun 11 19:12:22 volumio systemd[1]: shairport-sync.service: main process exited, code=exited, status=216/GROUP
Jun 11 19:12:22 volumio systemd[1]: Unit shairport-sync.service entered failed state.
Jun 11 19:12:22 volumio volumio[1073]: info: Upmpdcli Daemon Started
Jun 11 19:12:22 volumio volumio[1073]: info: Shairport-Sync Started
Jun 11 19:12:22 volumio volumio[1073]: Error adding Membership: Error: addMembership EINVAL
Jun 11 19:12:22 volumio volumio[1073]: info: Shairport-Sync Started
Jun 11 19:12:23 volumio volumio[1073]: info: CoreCommandRouter::volumioGetState
Jun 11 19:12:23 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin bluetooth to plan superstar
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin metavolumio to plan superstar
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin cd_controller to plan superstar
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin smart_inputs to plan superstar
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin hi_res_audio to plan superstar
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin bluetooth to plan virtuoso
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Adding plugin cd_controller to plan virtuoso
Jun 11 19:12:23 volumio volumio[1073]: info: Adding plugin bluetooth to MyMusic Plugins
Jun 11 19:12:23 volumio volumio[1073]: info: Adding plugin cd_controller to MyMusic Plugins
Jun 11 19:12:23 volumio volumio[1073]: info: Adding plugin smart_inputs to MyMusic Plugins
Jun 11 19:12:23 volumio volumio[1073]: info: [MyVolumio PluginManager] Loading plugin "my_volumio"...
Jun 11 19:12:26 volumio volumio[1073]: info: [MyVolumio PluginManager] Loading plugin "streaming_services"...
Jun 11 19:12:27 volumio volumio[1073]: info: [MyVolumio PluginManager] MyVolumio plugin successfully loaded
Jun 11 19:12:27 volumio volumio[1073]: info: [MyVolumio PluginManager] Starting plugin system_controller.my_volumio
Jun 11 19:12:27 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Jun 11 19:12:27 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Jun 11 19:12:27 volumio volumio[1073]: info: Starting MyVolumio Remote Streaming Endpoints
Jun 11 19:12:27 volumio volumio[1073]: info: [MyVolumio PluginManager] Streaming Services plugin successfully loaded
Jun 11 19:12:27 volumio volumio[1073]: info: [MyVolumio PluginManager] Starting plugin music_service.streaming_services
Jun 11 19:12:27 volumio volumio[1073]: info: Streaming services startup
Jun 11 19:12:27 volumio volumio[1073]: info: Starting Streaming Daemon
Jun 11 19:12:27 volumio volumio[1073]: info: MyVolumio not started
Jun 11 19:12:27 volumio volumio[1073]: info: Initializing device activation check
Jun 11 19:12:27 volumio sudo[1452]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart volumio-streaming-daemon.service
Jun 11 19:12:27 volumio sudo[1452]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 11 19:12:27 volumio systemd[1]: Stopping Volumio Streaming Daemon...
Jun 11 19:12:27 volumio volumio[1073]: info: [MyVolumio PluginManager] MyVolumio plugin successfully started
Jun 11 19:12:27 volumio systemd[1]: Starting Volumio Streaming Daemon...
Jun 11 19:12:27 volumio systemd[1]: Started Volumio Streaming Daemon.
Jun 11 19:12:27 volumio sudo[1452]: pam_unix(sudo:session): session closed for user root
Jun 11 19:12:27 volumio volumio-streaming-daemon[1458]: ############################
Jun 11 19:12:27 volumio volumio-streaming-daemon[1458]: # Volumio Streaming Daemon #
Jun 11 19:12:27 volumio volumio-streaming-daemon[1458]: # Running on port 7777     #
Jun 11 19:12:27 volumio volumio-streaming-daemon[1458]: ############################
Jun 11 19:12:27 volumio volumio-streaming-daemon[1458]: Environment: production
Jun 11 19:12:29 volumio volumio-remote-updater[639]: [2020-06-11 19:12:29] [connect] Successful connection
Jun 11 19:12:29 volumio volumio-remote-updater[639]: [2020-06-11 19:12:29] [connect] WebSocket Connection 127.0.0.1:3000 v-2 "WebSocket++/0.5.1" /socket.io/?EIO=4&transport=websocket&t=1591902749 101
Jun 11 19:12:30 volumio volumio-streaming-daemon[1458]: Environment: production
Jun 11 19:12:30 volumio volumio[1073]: info: Fetching Streaming Services browse cache
Jun 11 19:12:30 volumio volumio[1073]: info: CoreCommandRouter::volumioRemoveToBrowseSourcesTIDAL
Jun 11 19:12:30 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jun 11 19:12:30 volumio volumio[1073]: info: CoreCommandRouter::volumioRemoveToBrowseSourcesQOBUZ
Jun 11 19:12:30 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::volumioGetState
Jun 11 19:12:35 volumio volumio[1073]: info: CorePlayQueue::getTrack 0
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: multiroom , getMultiroom
Jun 11 19:12:35 volumio volumio[1073]: info: Listing playlists
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: appearance , getUiSettings
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: wizard , getShowWizard
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getShowWizard
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getPrivacySettings
Jun 11 19:12:35 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioStatus
Jun 11 19:12:44 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
Jun 11 19:12:44 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Jun 11 19:13:16 volumio volumio[1073]: info: CoreCommandRouter::getUIConfigOnPlugin

###SAVED PLUGIN SETTINGS###

Jun 11 19:13:16 volumio volumio[1073]: info: Loading settings page...
Jun 11 19:13:16 volumio volumio[1073]: info: [Rotary encoder] 1/4 settings loaded
Jun 11 19:13:16 volumio volumio[1073]: info: [Rotary encoder] 2/4 settings loaded
Jun 11 19:13:16 volumio volumio[1073]: info: [Rotary encoder] 3/4 settings loaded
Jun 11 19:13:16 volumio volumio[1073]: info: [Rotary encoder] 4/4 settings loaded
Jun 11 19:13:24 volumio volumio[1073]: info: CALLMETHOD: user_interface rotaryencoder updateGlobalSettings [object Object]
Jun 11 19:13:24 volumio volumio[1073]: info: CoreCommandRouter::executeOnPlugin: rotaryencoder , updateGlobalSettings`

**Comment by Saiyato** [comment]
I'm inclined to say you're running v1.2.2, can you config this please? You can see it in overview, if so, you're not running the latest version, which causes your problem (b/c you don't have a switch configured, this is a known and solved bug).

**Comment by MrPi3141** [comment]
Thanks, I am running version 2.777, as in the attached photo.
![image](https://user-images.githubusercontent.com/48841401/84805652-82d77880-affc-11ea-8dc5-6d088cb2b6eb.png)

**Comment by Saiyato** [comment]
Hi buddy,

I mean the version of the plugin, you can view that in the plugins page (on the tab "installed plugins")
It should read version 1.2.4 there, otherwise you're a release behind unfortunately.

**Comment by MrPi3141** [comment]
Ahh, thanks! It is running version 1.2.2. I have managed to fix the issue by using the advice from https://github.com/Saiyato/volumio-rotary-encoder-plugin/issues/18 - adding a non-existent switch pin to the encoder settings. Thanks for all your help though! I will now close this issue.
